version: '2'
services:
  flume:
    build: ./flume
    ports:
    - 9999:9999
    depends_on: 
      - spark
  generator:
    build: ./generator
    depends_on: 
      - flume 
  db:
    build: ./db
    ports:
    - 5432:5432
  monitor:
    build: ./monitor
    depends_on:
      - db
  spark:
    build: ./spark
    ports:
      - 8888:8888
    depends_on:
      - db 
